spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/novelist
    username: ${psql.user}
    password: ${psql.password}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
          github:
            clientId: ${github.client.id}
            clientSecret: ${github.client.secret}
image:
  local: true
onesignal:
  id: ${onesignal.id}